version: '{build}'
branches:
  only:
  - main
  
image: Visual Studio 2022

platform:
  - x64

environment:
  BOOST_ROOT: C:\Libraries\boost_1_77_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_77_0\lib64-msvc-14.3

configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive

before_build:
    - cmake -DVIA_HTTPLIB_BUILD_TESTS=ON -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
