name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Boost and Coveralls
      run: |
        sudo apt-get update -qq
        sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DVIA_HTTPLIB_UNIT_TESTS=ON -DVIA_HTTPLIB_COVERAGE=ON

    - name: Make
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ./via-httplib_test

    - name: Coverage
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: lcov -c -d . -o coverage.info

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: ${{github.workspace}}/build/coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
